version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: pgdb
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: nest_user
      POSTGRES_PASSWORD: lozinka123
      POSTGRES_DB: mydb
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
